[project]
name = "my-discord-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "google-adk>=0.5.0",
    "mypy>=1.15.0",
]
